### ISSUE TITLE
Not installable in QGIS 3

### ISSUE THREAD

**Issue by kgraefe** [datalyze-solutions/TileMapScaleLevels#2]
The plugin is not available in the plugin list in QGIS and manual installation from the ZIP file fails with the following error message:

```
ModuleNotFoundError: No module named 'tilemapscaleplugin' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/kgraefe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TileMapScaleLevels\__init__.py", line 26, in classFactory
    from tilemapscaleplugin import TileMapScalePlugin
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'tilemapscaleplugin'
```

**Comment by kgraefe** [comment]
FYI, I am working on Qgis3 compatibility at https://github.com/kgraefe/TileMapScaleLevels/tree/develop

It is working quite well already. I just have to figure out why it's crashing when zooming out too far.
